kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx4g
org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
org.gradle.caching=true
android.useAndroidX=true
# iosX64 is built for Intel simulators but cannot be tested on Apple silicon hosts.
kotlin.native.ignoreDisabledTargets=true
