package xyz.felixb.dicebear.internal

import xyz.felixb.dicebear.Canvas
import xyz.felixb.dicebear.Component
import xyz.felixb.dicebear.ElementNode
import xyz.felixb.dicebear.Style
import xyz.felixb.dicebear.obj
import kotlin.math.floor
import kotlin.random.Random

/**
 * Walks a style's element tree and produces the SVG markup. Single use: it accumulates `<defs>`
 * entries and per-render caches.
 */
internal class Renderer(private val style: Style, private val resolver: Resolver) {
    // Insertion ordered; re-assigning a key keeps its position (like the JS Map).
    private val defs = LinkedHashMap<String, String>()
    private val seedHash: String by lazy {
        fnv1aHex("${style.meta.sourceName ?: ""}:${resolver.seed()}")
    }
    private val initials: String by lazy { initialsFromSeed(resolver.seed()) }
    private val randomSuffix: String by lazy {
        floor(Random.nextDouble() * 0xffffff).toLong().toString(16).padStart(6, '0')
    }
    private val keyframesCss = mutableListOf<String>()
    private val animationCss = mutableListOf<String>()
    private val keyframesByContent = HashMap<String, String>()
    private var keyframesCounter = 0
    private var animationClassCounter = 0

    fun render(): String {
        val canvas = style.canvas
        val background = renderBackground(canvas)
        var body = renderElements(canvas.elements)

        // Scale and flip around the center, then rotate, translate, and clip (outermost).
        body = applyScale(body, canvas)
        body = applyFlip(body, canvas)
        body = applyRotate(body, canvas)
        body = applyTranslate(body, canvas)
        body = applyBorderRadius(background + body, canvas)

        registerAnimationStyle()

        val metadata = licenseXml(style.meta)
        val defsMarkup = if (defs.isNotEmpty()) "<defs>${defs.values.joinToString("")}</defs>" else ""

        // Size before title and root attributes: the snapshot records keys in resolution order.
        val size = resolver.size()
        val escapedTitle = resolver.title()?.let(::escapeXml)

        val attrs = mutableListOf(
            "xmlns=\"http://www.w3.org/2000/svg\"",
            "viewBox=\"0 0 ${formatNumber(canvas.width)} ${formatNumber(canvas.height)}\"",
        )

        val rootAttributes = renderAttributes(style.attributes())
        if (rootAttributes.isNotEmpty()) attrs += rootAttributes.trimStart()

        if (escapedTitle != null) {
            attrs += "role=\"img\""
            attrs += "aria-label=\"$escapedTitle\""
        } else {
            attrs += "aria-hidden=\"true\""
        }

        if (size != null) {
            val sizeValue = formatNumber(size)
            attrs += "width=\"$sizeValue\""
            attrs += "height=\"$sizeValue\""
        }

        val titleElement = if (escapedTitle != null) "<title>$escapedTitle</title>" else ""

        var svg = "<svg ${attrs.joinToString(" ")}>" +
            "<!-- Generated by DiceBear (https://www.dicebear.com) -->" +
            "$metadata$defsMarkup$titleElement$body</svg>"

        if (resolver.idRandomization()) svg = randomizeIds(svg)

        return svg
    }

    private fun applyFlip(body: String, canvas: Canvas): String {
        val w = formatNumber(canvas.width)
        val h = formatNumber(canvas.height)
        val transform = when (resolver.flip()) {
            "horizontal" -> "translate($w, 0) scale(-1, 1)"
            "vertical" -> "translate(0, $h) scale(1, -1)"
            "both" -> "translate($w, $h) scale(-1, -1)"
            else -> return body
        }
        return "<g transform=\"$transform\">$body</g>"
    }

    private fun applyScale(body: String, canvas: Canvas): String {
        val scale = resolver.scale()
        if (scale == 1.0) return body

        val cx = canvas.width / 2
        val cy = canvas.height / 2
        return "<g transform=\"translate(${formatNumber(cx)}, ${formatNumber(cy)}) " +
            "scale(${formatNumber(scale)}) " +
            "translate(${formatNumber(-cx)}, ${formatNumber(-cy)})\">$body</g>"
    }

    /** Always clips, so transformed content cannot bleed past the canvas. */
    private fun applyBorderRadius(body: String, canvas: Canvas): String {
        val radius = resolver.borderRadius()
        val id = "clip-$seedHash"
        val rx = formatNumber(radius / 100 * canvas.width)
        val ry = formatNumber(radius / 100 * canvas.height)

        defs[id] = "<clipPath id=\"$id\">" +
            "<rect width=\"${formatNumber(canvas.width)}\" height=\"${formatNumber(canvas.height)}\" rx=\"$rx\" ry=\"$ry\"/>" +
            "</clipPath>"

        return "<g clip-path=\"url(#$id)\">$body</g>"
    }

    private fun applyRotate(body: String, canvas: Canvas): String {
        val rotate = resolver.rotate()
        if (rotate == 0.0) return body

        return "<g transform=\"rotate(${formatNumber(rotate)}, " +
            "${formatNumber(canvas.width / 2)}, ${formatNumber(canvas.height / 2)})\">$body</g>"
    }

    private fun applyTranslate(body: String, canvas: Canvas): String {
        val tx = resolver.translateX()
        val ty = resolver.translateY()
        if (tx == 0.0 && ty == 0.0) return body

        val x = formatNumber(tx / 100 * canvas.width)
        val y = formatNumber(ty / 100 * canvas.height)
        return "<g transform=\"translate($x, $y)\">$body</g>"
    }

    /** The first resolver call of a render: `backgroundColorFill`/`backgroundColor` open the snapshot. */
    private fun renderBackground(canvas: Canvas): String {
        if (resolver.color("background").isEmpty()) return ""

        return "<rect width=\"${formatNumber(canvas.width)}\" height=\"${formatNumber(canvas.height)}\" " +
            "fill=\"${escapeXml(resolveColorReference("background"))}\"/>"
    }

    /** Suffixes every id declaration and reference so identical avatars don't collide in one document. */
    private fun randomizeIds(svg: String): String {
        val ids = ID_DECLARATION.findAll(svg).map { it.groupValues[1] }.toCollection(LinkedHashSet())
        if (ids.isEmpty()) return svg

        val pattern = Regex("(id=\"|url\\(#|href=\"#)(${ids.joinToString("|") { escapeRegex(it) }})(\"|\\))")
        return pattern.replace(svg) { m -> "${m.groupValues[1]}${m.groupValues[2]}-$randomSuffix${m.groupValues[3]}" }
    }

    private fun renderElements(elements: List<ElementNode>): String = elements.joinToString("") { renderElement(it) }

    private fun renderElement(element: ElementNode): String = when (element.type) {
        "element" -> renderSvgElement(element)
        "text" -> renderTextElement(element)
        "component" -> renderComponentElement(element)
        else -> ""
    }

    /** Element and attribute names come from the schema allowlist; only values are escaped. */
    private fun renderSvgElement(element: ElementNode): String {
        val name = element.name
        if (name.isNullOrEmpty()) return ""

        if (name == "defs") {
            for (child in element.children) {
                val rendered = renderElement(child)
                if (rendered.isNotEmpty()) {
                    val id = child.attributes?.get("id")
                    defs[if (id is String) id else "_${defs.size}"] = rendered
                }
            }
            return ""
        }

        val children = renderElements(element.children)

        // A wrapper whose children all rendered to nothing is dropped, unless it carries an id.
        if (children.isEmpty() && element.children.isNotEmpty() && element.attributes?.get("id") == null) {
            return ""
        }

        val active = playingAnimations(element)
        val attrs = renderAttributes(attributesWithoutAnimatedOpacity(element.attributes, active))

        if (children.isEmpty()) return applyAnimations("<$name$attrs/>", element, active)

        return applyAnimations("<$name$attrs>$children</$name>", element, active)
    }

    private fun renderTextElement(element: ElementNode): String {
        val value = element.value ?: return ""
        return escapeXml(resolveValue(value))
    }

    /**
     * Emits a `<use>` referencing a `<defs>` entry with the variant body (shared between aliases).
     * An authored `transform` is prepended to the per-component transforms.
     */
    private fun renderComponentElement(element: ElementNode): String {
        val componentName = element.name ?: return ""
        val variantName = resolver.variant(componentName)
        if (variantName.isNullOrEmpty()) return ""

        val component = style.components[componentName] ?: return ""
        val variant = component.variants[variantName] ?: return ""

        val id = "${component.sourceName}-$variantName-$seedHash"

        if (!defs.containsKey(id)) {
            val body = renderElements(variant.elements)
            defs[id] = "<g id=\"$id\">$body</g>"
        }

        val transforms = buildTransforms(component)
        val active = playingAnimations(element)
        val userAttributes = attributesWithoutAnimatedOpacity(element.attributes, active)
        var merged = userAttributes

        if (transforms.isNotEmpty()) {
            val userTransform = userAttributes?.get("transform")
            val parts = if (userTransform is String && userTransform.isNotEmpty()) listOf(userTransform) + transforms else transforms
            merged = LinkedHashMap(userAttributes ?: emptyMap<String, Any?>()).also { it["transform"] = parts.joinToString(" ") }
        }

        return applyAnimations("<use${renderAttributes(merged)} href=\"#$id\"/>", element, active)
    }

    /** translate, rotate, then scale (innermost); empty when all are identity. */
    private fun buildTransforms(component: Component): List<String> {
        val (rotate, translateX, translateY, scale) = resolver.componentTransform(component.name)

        if (translateX == 0.0 && translateY == 0.0 && rotate == 0.0 && scale == 1.0) return emptyList()

        val transforms = mutableListOf<String>()
        val cx = component.width / 2
        val cy = component.height / 2
        val cxValue = formatNumber(cx)
        val cyValue = formatNumber(cy)

        if (translateX != 0.0 || translateY != 0.0) {
            val x = formatNumber(translateX / 100 * component.width)
            val y = formatNumber(translateY / 100 * component.height)
            transforms += "translate($x, $y)"
        }

        if (rotate != 0.0) transforms += "rotate(${formatNumber(rotate)}, $cxValue, $cyValue)"

        if (scale != 1.0) {
            transforms += "translate($cxValue, $cyValue) scale(${formatNumber(scale)}) " +
                "translate(${formatNumber(-cx)}, ${formatNumber(-cy)})"
        }

        return transforms
    }

    /** ` a="b" c="d"` in insertion order, or an empty string. */
    private fun renderAttributes(attributes: Map<String, Any?>?): String {
        if (attributes == null) return ""

        val parts = attributes.entries
            .filter { it.value != null }
            .map { (key, value) -> "$key=\"${escapeXml(resolveAttributeValue(value!!))}\"" }

        return if (parts.isEmpty()) "" else " " + parts.joinToString(" ")
    }

    private fun resolveAttributeValue(value: Any): String {
        if (value is String) return value
        val reference = obj(value)
        val name = reference["name"] as String
        return if (reference["type"] == "color") resolveColorReference(name) else resolveVariable(name)
    }

    /** A hex string, or a `url(#…)` reference to a gradient registered in `<defs>`. */
    private fun resolveColorReference(name: String): String {
        val colors = resolver.color(name)
        val fill = resolver.colorFill(name)

        if (fill == "solid" || colors.size <= 1) return colors.firstOrNull() ?: "none"

        return buildGradientDef(name, colors, fill)
    }

    private fun buildGradientDef(name: String, colors: List<String>, fill: String): String {
        val rotation = resolver.colorAngle(name)
        val id = "$name-color-$seedHash"
        val tag = if (fill == "linear") "linearGradient" else "radialGradient"
        val rotateAttr = if (rotation != 0.0) " gradientTransform=\"rotate(${formatNumber(rotation)}, 0.5, 0.5)\"" else ""

        val stops = StringBuilder()
        for (i in colors.indices) {
            val offset = formatNumber(i.toDouble() / (colors.size - 1) * 100)
            stops.append("<stop offset=\"$offset%\" stop-color=\"${escapeXml(colors[i])}\"/>")
        }

        defs[id] = "<$tag id=\"$id\"$rotateAttr>$stops</$tag>"

        return "url(#$id)"
    }

    private fun resolveValue(value: Any): String {
        if (value is String) return value
        val reference = obj(value)
        return if (reference["type"] == "variable") resolveVariable(reference["name"] as String) else ""
    }

    private fun resolveVariable(name: String): String = when (name) {
        // The first code point (not code unit), so supplementary-plane initials stay well-formed.
        "initial" -> when {
            initials.isEmpty() -> ""
            initials.length > 1 && initials[0].isHighSurrogate() && initials[1].isLowSurrogate() -> initials.substring(0, 2)
            else -> initials.substring(0, 1)
        }
        "initials" -> initials
        "fontWeight" -> formatNumber(resolver.fontWeight())
        "fontFamily" -> resolver.fontFamily()
        else -> ""
    }

    /**
     * Namespaces animation class and keyframe names. Includes speed, delay and the state of every
     * named timeline, plus the random suffix under `idRandomization`.
     */
    private val animationHash: String by lazy {
        val random = if (resolver.idRandomization()) ":$randomSuffix" else ""

        val states = style.animationNames.map { name ->
            if (resolver.animationPlays(name)) {
                "$name:${formatNumber(resolver.animationSpeedFor(name))}:${formatNumber(resolver.animationDelayFor(name))}"
            } else {
                "$name:off"
            }
        }
        val named = if (states.isEmpty()) "" else ":" + states.joinToString(",")

        fnv1aHex(
            "${style.meta.sourceName ?: ""}:${resolver.seed()}:" +
                "${formatNumber(resolver.animationSpeed())}:${formatNumber(resolver.animationDelay())}$named$random",
        )
    }

    /** Wraps markup in one `<g class>` per animated track (block 0 outermost, canonical track order). */
    private fun applyAnimations(markup: String, element: ElementNode, active: List<Map<String, Any?>>): String {
        if (markup.isEmpty() || active.isEmpty()) return markup

        val classes = mutableListOf<String>()
        var opacityWrapper = -1

        for (animation in active) {
            val tracks = obj(animation["tracks"])
            for (track in TRACK_ORDER) {
                val trackData = tracks[track] as? Map<*, *> ?: continue
                if (track == "opacity") opacityWrapper = classes.size
                classes += buildAnimationCss(animation, track, trackData["keyframes"] as List<*>)
            }
        }

        val restingOpacity = element.attributes?.get("opacity")
        var result = markup

        for (i in classes.indices.reversed()) {
            val opacity = if (i == opacityWrapper && restingOpacity != null) renderAttributes(mapOf("opacity" to restingOpacity)) else ""
            result = "<g class=\"${classes[i]}\"$opacity>$result</g>"
        }

        return result
    }

    /** The element's timelines that play; reads the global switch whenever the node animates. */
    private fun playingAnimations(element: ElementNode): List<Map<String, Any?>> {
        val animations = element.animations
        if (animations.isEmpty()) return emptyList()

        resolver.animation()

        return animations.filter { resolver.animationPlays(it["name"] as? String) }
    }

    /** An animated opacity track takes over the element's own `opacity` attribute. */
    private fun attributesWithoutAnimatedOpacity(
        attributes: Map<String, Any?>?,
        active: List<Map<String, Any?>>,
    ): Map<String, Any?>? {
        if (attributes == null || attributes["opacity"] == null) return attributes

        for (animation in active) {
            if (obj(animation["tracks"])["opacity"] != null) return LinkedHashMap(attributes).also { it.remove("opacity") }
        }

        return attributes
    }

    /** Registers the (content-deduplicated) `@keyframes` and the class rule; returns the class name. */
    private fun buildAnimationCss(animation: Map<String, Any?>, track: String, keyframes: List<*>): String {
        val defaultEasing = animation["easing"] ?: "linear"
        val body = keyframesBody(track, keyframes, defaultEasing)

        val keyframesName = keyframesByContent.getOrPut(body) {
            "dbk-$animationHash-${keyframesCounter++}".also { keyframesCss += "@keyframes $it{$body}" }
        }

        val name = animation["name"] as? String
        val speed = resolver.animationSpeedFor(name)
        val duration = formatNumber((animation["duration"] as Number).toDouble() / speed)

        // The user's offset is wall-clock seconds, added after the speed scaled the authored delay.
        val delay = formatNumber(((animation["delay"] as? Number)?.toDouble() ?: 0.0) / speed + resolver.animationDelayFor(name))
        val iterations = (animation["iterations"] as? Number)?.let { formatNumber(it.toDouble()) } ?: "infinite"
        val direction = DIRECTION_CSS[animation["direction"]] ?: "normal"
        val fill = animation["fill"] as? String ?: "none"

        val originCss = if (track == "rotate" || track == "scaleX" || track == "scaleY") {
            val origin = obj(animation["origin"])
            val x = formatNumber((origin["x"] as? Number)?.toDouble() ?: 50.0)
            val y = formatNumber((origin["y"] as? Number)?.toDouble() ?: 50.0)
            "transform-box:fill-box;transform-origin:$x% $y%;"
        } else {
            ""
        }

        val className = "dba-$animationHash-${animationClassCounter++}"

        animationCss += ".$className{${originCss}animation:${duration}s " +
            "${easingCss(defaultEasing)} ${delay}s $iterations $direction $fill $keyframesName}"

        return className
    }

    private class Keyframe(val at: Double, val value: Double, val easing: Any?)

    /** Pads the endpoints to 0%/100% and emits per-keyframe easing only where it differs. */
    private fun keyframesBody(track: String, keyframes: List<*>, defaultEasing: Any): String {
        val list = keyframes.map {
            val k = obj(it)
            Keyframe((k["at"] as Number).toDouble(), (k["value"] as Number).toDouble(), k["easing"])
        }.toMutableList()

        if (list.first().at > 0) list.add(0, Keyframe(0.0, list.first().value, null))
        val last = list.last()
        if (last.at < 100) list.add(Keyframe(100.0, last.value, null))

        val defaultCss = easingCss(defaultEasing)
        val body = StringBuilder()

        list.forEachIndexed { i, keyframe ->
            val easing = keyframe.easing
            val css = if (easing != null && i < list.size - 1) easingCss(easing) else defaultCss
            val timing = if (css != defaultCss) ";animation-timing-function:$css" else ""
            body.append("${formatNumber(keyframe.at)}%{${trackDeclaration(track, keyframe.value)}$timing}")
        }

        return body.toString()
    }

    private fun trackDeclaration(track: String, value: Double): String {
        val v = formatNumber(value)
        return when (track) {
            "translateX" -> "transform:translateX(${v}px)"
            "translateY" -> "transform:translateY(${v}px)"
            "rotate" -> "transform:rotate(${v}deg)"
            "scaleX" -> "transform:scaleX($v)"
            "scaleY" -> "transform:scaleY($v)"
            else -> "opacity:$v"
        }
    }

    private fun easingCss(easing: Any): String {
        if (easing is String) return EASING_KEYWORD_CSS[easing] ?: "linear"

        val b = obj(easing)
        fun n(key: String) = formatNumber((b[key] as Number).toDouble())
        return "cubic-bezier(${n("x1")}, ${n("y1")}, ${n("x2")}, ${n("y2")})"
    }

    /** One `<style>` def wrapped in a reduced-motion media query; takes the next free key. */
    private fun registerAnimationStyle() {
        if (keyframesCss.isEmpty()) return

        var key = "animation-style"
        while (defs.containsKey(key)) key += "-"

        defs[key] = "<style>@media (prefers-reduced-motion:no-preference)" +
            "{${keyframesCss.joinToString("")}${animationCss.joinToString("")}}</style>"
    }

    private companion object {
        val TRACK_ORDER = listOf("translateX", "translateY", "rotate", "scaleX", "scaleY", "opacity")

        val DIRECTION_CSS = mapOf(
            "normal" to "normal",
            "reverse" to "reverse",
            "alternate" to "alternate",
            "alternateReverse" to "alternate-reverse",
        )

        val EASING_KEYWORD_CSS = mapOf(
            "linear" to "linear",
            "ease" to "ease",
            "easeIn" to "ease-in",
            "easeOut" to "ease-out",
            "easeInOut" to "ease-in-out",
            "hold" to "step-end",
        )

        val ID_DECLARATION = Regex("\\bid=\"([^\"]+)\"")

        /** Backslash-escapes `.*+?^${}()|[]\` (portable, unlike `\Q…\E`). */
        fun escapeRegex(s: String): String = buildString {
            for (c in s) {
                if (c in ".*+?^\${}()|[]\\") append('\\')
                append(c)
            }
        }
    }
}
